[package]
name = "openbim-icdd"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
authors = ["point-grey"]
repository = "https://github.com/openbimrs/icdd"
readme = "README.md"
description = "ISO 21597 ICDD (Information Container for linked Document Delivery)."
keywords = ["bim", "openbim", "ifc", "aec"]
categories = ["parser-implementations", "data-structures"]

[dependencies]
openbim-core = "0.1.0"
